const ALBUMS = [
    //album example 1
    {
        name: 'Canter',
        artist: 'Gerry Cinnamon',
        album: 'The Bonny',
        id: 0
    },
    {
        name: 'Sun Queen',
        artist: 'Gerry Cinnamon',
        album: 'The Bonny',
        id: 1
    },
    {
        name: 'Dark Days',
        artist: 'Gerry Cinnamon',
        album: 'The Bonny',
        id: 2
    },
    {
        name: 'The Bonny',
        artist: 'Gerry Cinnamon',
        album: 'The Bonny',
        id: 3
    },
    {
        name: "Where We're Going",
        artist: 'Gerry Cinnamon',
        album: 'The Bonny',
        id: 4
    },
    {
        name: 'Head in the Clouds',
        artist: 'Gerry Cinnamon',
        album: 'The Bonny',
        id: 5
    },
    //ALBUM 2
    {
        name: 'Polyamorous',
        artist: 'Breaking Benjamin',
        album: 'Saturate',
        id: 6
    },
    {
        name: 'Skin',
        artist: 'Breaking Benjamin',
        album: 'Saturate',
        id: 7
    },
    {
        name: 'Medicate',
        artist: 'Breaking Benjamin',
        album: 'Saturate',
        id: 8
    }
];